/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.TransaksiController;
/**
 *
 * @author RAIHAN
 */
public class TransaksiFrame extends javax.swing.JFrame {
    private TransaksiController controller;  
    /**
     * Creates new form TransaksiFrame
     */
    public TransaksiFrame() {
        initComponents();
        controller = new TransaksiController(this);  
    }
    
    /* ===== Getter ===== */
    public javax.swing.JComboBox getCmbPelanggan() { return cmbPelanggan; }
    public javax.swing.JComboBox getCmbMotor()     { return cmbMotor; }

    public javax.swing.JTextField                getTxtQty()        { return txtQty; }
    public javax.swing.JTable                   getTblDetail()     { return JTDetailTransaksi; }
    public javax.swing.JLabel                   getLblTotal()      { return lblTotal; }

    // Variables declaration
    private javax.swing.JComboBox cmbPelanggan;
    private javax.swing.JComboBox cmbMotor;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        lblHarga = new javax.swing.JLabel();
        lblSub = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTDetailTransaksi = new javax.swing.JTable();
        Total = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnBayar = new javax.swing.JButton();
        cmbPelanggan1 = new javax.swing.JComboBox();
        cmbMotor1 = new javax.swing.JComboBox();

        jLabel9.setText("jLabel9");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("PENJUALAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel2.setText("TANGGAL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setText("PELANGGAN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel4.setText("MOTOR");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel5.setText("QTY");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel6.setText("HARGA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jLabel7.setText("SUBTOTAL");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));
        getContentPane().add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 120, -1));
        getContentPane().add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 120, -1));

        lblHarga.setText("...");
        getContentPane().add(lblHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        lblSub.setText("...");
        getContentPane().add(lblSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        btnTambah.setText("TAMBAH");
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        JTDetailTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTDetailTransaksi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 490, 170));

        Total.setText("TOTAL");
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        lblTotal.setText("...");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        btnBayar.setText("BAYAR");
        getContentPane().add(btnBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, -1));

        cmbPelanggan1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPelanggan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPelanggan1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPelanggan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 120, -1));

        cmbMotor1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbMotor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 120, -1));

        setSize(new java.awt.Dimension(546, 496));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPelanggan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPelanggan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPelanggan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTDetailTransaksi;
    private javax.swing.JLabel Total;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox cmbMotor1;
    private javax.swing.JComboBox cmbPelanggan1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblSub;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
